# Generated by Django 2.2.7 on 2019-11-11 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20191108_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='skill_thumbnails/'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name',
            field=models.CharField(default='new skill', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='width',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.SkillCategory'),
        ),
    ]
