# Generated by Django 2.2.7 on 2019-11-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20191111_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'verbose_name_plural': 'skill categories'},
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='icon',
            field=models.TextField(default='<i className="fas fa-desktop"></i>', max_length=200),
        ),
    ]
