# Generated by Django 2.2.7 on 2019-11-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20191111_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillcategory',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
