# Generated by Django 2.2.7 on 2019-11-12 06:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20191111_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExpCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='exp_cards/')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('desc', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ExpCategory')),
            ],
        ),
    ]
