# Generated by Django 2.2.7 on 2019-11-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_expcard_expcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expcategory',
            options={'verbose_name_plural': 'exp categories'},
        ),
        migrations.AddField(
            model_name='expcategory',
            name='bg_color',
            field=models.TextField(default='green accent-4', max_length=50),
        ),
        migrations.AddField(
            model_name='expcategory',
            name='icon',
            field=models.TextField(default='<i className="fas fa-graduation-cap"></i>', max_length=200),
        ),
    ]
