# Generated by Django 2.2.7 on 2019-11-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20191112_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcategory',
            name='tag',
            field=models.CharField(default='#edu', max_length=10),
        ),
    ]
