# Generated by Django 2.2.7 on 2019-11-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_skillcategory_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillcategory',
            name='tag',
        ),
        migrations.AddField(
            model_name='expcategory',
            name='tag',
            field=models.CharField(default='#edu', max_length=10),
        ),
    ]
