# Generated by Django 2.2.7 on 2019-11-17 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20191112_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='projects/')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('desc', models.TextField()),
                ('tag', models.CharField(default='#edu', max_length=10)),
                ('link', models.URLField()),
            ],
        ),
    ]
